name: Shellcheck
on:
  pull_request:
    paths:
      - "rootfs/setup*"

permissions:
  contents: read

jobs:
  lint:
    name: Shell Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
